import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { HiOutlineComputerDesktop, HiOutlineKey, HiOutlinePlus, HiOutlineShieldCheck, HiOutlineTrash, HiOutlineUserGroup } from 'react-icons/hi2';
import { changePassword, createUser, getSessions, getUsers, revokeSession, updateUser } from '../../api/securityApi';
import { useAuth } from '../../context/AuthContext';
import { formatDateTime } from '../../utils/dateUtils';
import './SecurityPage.css';

const deviceName=(agent='')=>{if(agent.includes('Edg/'))return 'Microsoft Edge';if(agent.includes('Chrome/'))return 'Google Chrome';if(agent.includes('Firefox/'))return 'Firefox';if(agent.includes('Safari/'))return 'Safari';return 'Browser session';};

export default function SecurityPage(){
 const {user,isSuperAdmin,logoutUser}=useAuth();const navigate=useNavigate();const [sessions,setSessions]=useState([]);const [users,setUsers]=useState([]);const [loading,setLoading]=useState(true);const [showUser,setShowUser]=useState(false);const [userForm,setUserForm]=useState({fullName:'',email:'',password:'',role:'VIEWER'});const [password,setPassword]=useState({currentPassword:'',newPassword:'',confirm:''});
 const load=async()=>{setLoading(true);try{const sessionResponse=await getSessions();setSessions(sessionResponse.data||[]);if(isSuperAdmin()){const userResponse=await getUsers();setUsers(userResponse.data||[]);}}catch(error){toast.error(error.response?.data?.message||'Failed to load security settings');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const submitPassword=async(e)=>{e.preventDefault();if(password.newPassword!==password.confirm){toast.error('New passwords do not match');return;}try{await changePassword({currentPassword:password.currentPassword,newPassword:password.newPassword});toast.success('Password changed. Sign in again.');await logoutUser();navigate('/login');}catch(error){toast.error(error.response?.data?.message||'Could not change password');}};
 const removeSession=async(session)=>{if(!window.confirm('Revoke this session?'))return;await revokeSession(session.id);if(session.id===localStorage.getItem('sessionId')){await logoutUser();navigate('/login');return;}toast.success('Session revoked');load();};
 const submitUser=async(e)=>{e.preventDefault();try{await createUser(userForm);toast.success('User account created');setShowUser(false);setUserForm({fullName:'',email:'',password:'',role:'VIEWER'});load();}catch(error){toast.error(error.response?.data?.message||'Could not create user');}};
 const changeUser=async(target,patch)=>{try{await updateUser(target.id,patch);toast.success('User updated');load();}catch(error){toast.error(error.response?.data?.message||'Could not update user');}};
 return <div className="security-page"><div className="page-header"><div><h1>Security</h1><p>Manage your password, signed-in devices, administrators, and audit history.</p></div>{isSuperAdmin()&&<button className="btn btn-primary" onClick={()=>setShowUser(true)}><HiOutlinePlus/>Add User</button>}</div>
  <section className="security-summary"><article className="card"><span><HiOutlineShieldCheck/></span><div><small>Account role</small><strong>{user.role.replace('_',' ')}</strong><p>Signed in as {user.email}</p></div></article><article className="card"><span><HiOutlineComputerDesktop/></span><div><small>Active sessions</small><strong>{sessions.length}</strong><p>Refresh sessions that can access this account</p></div></article><article className="card"><span><HiOutlineUserGroup/></span><div><small>Managed users</small><strong>{isSuperAdmin()?users.length:'Admin only'}</strong><p>Role-based access is enforced by the API</p></div></article></section>
  <div className="security-grid"><section className="card security-panel"><div className="security-heading"><div><h2>Active sessions</h2><p>Revoke access from browsers you do not recognize.</p></div></div>{loading?<div className="loader"><div className="spinner"/></div>:<div className="session-list">{sessions.map(session=><article key={session.id}><span className="session-icon"><HiOutlineComputerDesktop/></span><div><strong>{deviceName(session.userAgent)} {session.id===localStorage.getItem('sessionId')&&<em>Current</em>}</strong><p>{session.ipAddress||'Unknown IP'} · Last used {formatDateTime(session.lastUsedAt)}</p><small>{session.userAgent}</small></div><button className="btn btn-ghost btn-icon text-danger" onClick={()=>removeSession(session)} title="Revoke session"><HiOutlineTrash/></button></article>)}</div>}</section>
   <section className="card security-panel"><div className="security-heading"><div><h2>Change password</h2><p>This revokes every active session after the change.</p></div></div><form className="security-password" onSubmit={submitPassword}><div className="input-group"><label>Current password</label><input className="input" type="password" required value={password.currentPassword} onChange={e=>setPassword({...password,currentPassword:e.target.value})}/></div><div className="input-group"><label>New password</label><input className="input" type="password" minLength={10} required value={password.newPassword} onChange={e=>setPassword({...password,newPassword:e.target.value})}/></div><div className="input-group"><label>Confirm new password</label><input className="input" type="password" minLength={10} required value={password.confirm} onChange={e=>setPassword({...password,confirm:e.target.value})}/></div><button className="btn btn-primary"><HiOutlineKey/>Change Password</button></form></section></div>
  {isSuperAdmin()&&<section className="card security-panel security-users"><div className="security-heading"><div><h2>Users and roles</h2><p>Only super admins can create accounts or change access levels.</p></div></div><div className="table-wrapper"><table className="table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Last login</th><th>Actions</th></tr></thead><tbody>{users.map(target=><tr key={target.id}><td><div className="security-user"><strong>{target.fullName}</strong><span>{target.email}</span></div></td><td><select className="select compact-select" value={target.role} onChange={e=>changeUser(target,{role:e.target.value})}><option>VIEWER</option><option>ADMIN</option><option>SUPER_ADMIN</option></select></td><td><span className={`badge ${target.active?'badge-active':'badge-revoked'}`}>{target.active?'Active':'Disabled'}</span></td><td>{formatDateTime(target.lastLoginAt)}</td><td><button className="btn btn-secondary btn-sm" disabled={target.email===user.email} onClick={()=>changeUser(target,{active:!target.active})}>{target.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div></section>}
  {showUser&&<div className="modal-overlay" onClick={()=>setShowUser(false)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-header"><h2>Create user</h2><button className="btn btn-ghost btn-icon" onClick={()=>setShowUser(false)}>×</button></div><form onSubmit={submitUser}><div className="input-group"><label>Full name</label><input className="input" required value={userForm.fullName} onChange={e=>setUserForm({...userForm,fullName:e.target.value})}/></div><div className="input-group mt-md"><label>Email</label><input className="input" type="email" required value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/></div><div className="input-group mt-md"><label>Temporary password</label><input className="input" type="password" minLength={10} required value={userForm.password} onChange={e=>setUserForm({...userForm,password:e.target.value})}/></div><div className="input-group mt-md"><label>Role</label><select className="select" value={userForm.role} onChange={e=>setUserForm({...userForm,role:e.target.value})}><option>VIEWER</option><option>ADMIN</option><option>SUPER_ADMIN</option></select></div><div className="modal-footer"><button type="button" className="btn btn-secondary" onClick={()=>setShowUser(false)}>Cancel</button><button className="btn btn-primary">Create User</button></div></form></div></div>}
 </div>;
}
